name: 'preview-apps'
on: # rebuild any PRs and main branch changes; test with local ngrok
  pull_request:
jobs:
  hasura-cloud-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hasura/hasura-cloud-preview-apps@ram/db-ssl-fix
        with:
          name: "preview-samp-home-food-${{github.env.GITHUB_HEAD_REF}}${{github.event.number}}"
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.POSTGRES_SERVER_CONNECTION_URI}}
            PG_ENV_VARS_FOR_HASURA=PG_DB_URL_1,PG_DB_URL_2
          hasuraProjectDirectoryPath: hasura-data
          region: us-west-1
          tier: cloud_free
          hasuraEnv: |
            PG_DATABASE_URL=${{secrets.POSTGRES_SERVER_CONNECTION_URI}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
      - uses: hasura/comment-progress@v2.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          id: preview_app_comment
          number: ${{github.event.number}}
          repository: "kikkupico/samp-home-food-dev-2"
          message: |
            Console URL available at ${{steps.hasura_cloud_preview.outputs.consoleURL}}
            GraphQL Endpoint available at ${{steps.hasura_cloud_preview.outputs.graphQLEndpoint}}